# define the basic access commands to put on IOS-XE device in process of ZTP

configure_basic_access_commands: |
  username ZTP privilege 15 password Cr8zyM@n
  ip domain name ZTP
    crypto key generate rsa modulus 4096
    line con 0
    logging synchronous
  line vty 0 15
    logging synchronous
    login local